# Generated by Django 5.2 on 2025-04-05 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customadmin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='description',
            field=models.TextField(default='', max_length=1000),
        ),
    ]
