# Generated by Django 5.2 on 2025-04-06 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customadmin', '0003_admin_review_certificate_store'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Certificate',
        ),
    ]
